export type Utilisateur = {
  id: string;
  email: string;
  prenom: string;
  nom: string;
  photoProfil?: string | null;
  dateNaissance?: string | null;
  lieuNaissance?: string | null;
  poste?: string | null;
  cin?: string | null;
  accroche?: string | null;
  atouts?: string | null;
};
export type Categorie = { id: string; nom: string; couleur: string; icone: string; createdAt: string };
export type Tag = { id: string; nom: string };
export type PieceJointe = { id: string; nomOriginal: string; nomFichier: string; typeMime: string; taille: number; createdAt: string };
export type Note = {
  id: string;
  titre: string;
  contenu: string;
  couleur: string;
  estFavorite: boolean;
  estArchivee: boolean;
  estEpinglee: boolean;
  estSupprimee: boolean;
  supprimeeAt?: string | null;
  categorieId?: string;
  categorie?: Categorie | null;
  tags: { tag: Tag }[];
  piecesJointes?: PieceJointe[];
  createdAt: string;
  updatedAt: string;
};
export type ReponseApi<T> = { succes: boolean; donnees: T; message?: string };
